# Fastfile

fastlane_version "1.50.0"

default_platform :ios


platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


    # increment_build_number

    # xctool # run the tests of your app
  end

  desc "Runs all the tests"
  lane :test do
    scan(
        scheme: "MixAndMatchTests",
        device: "iPhone 6 Plus",
        code_coverage: true,
        clean: false
    )

    slather(
        proj: "MixAndMatchTests.xcodeproj",
        scheme: "MixAndMatchTests",
        input_format: "profdata",
        ignore: "../**/*/Xcode*"
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
